spring:
  application:
    name: demo-service
logging:
  level:
    root: info
    com.example: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info, heapdump
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
  metrics:
    tags:
      application: ${spring.application.name}