global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'demo-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'demo-service:8080' ]
  